### ISSUE TITLE
Add Round Type to Project's Applications

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/grants-stack#10]
As a Project Manager user should be able to see the Round Type for each round displayed in My Applications on the About tab.
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/a4a19a6b-34f5-42ce-97bc-8805b176f1a2)

**Comment by marcelorubini** [comment]
As shown in the PR, just for having record in the issue:

![Screenshot from 2023-07-20 11-10-30](https://github.com/BootNodeDev/grants-stack/assets/2502507/3a0dc6dd-f424-462e-8377-1cb095484960)
