### ISSUE TITLE
As a manager I need to create a direct round

### ISSUE THREAD

**Issue by nicosampler** [BootNodeDev/grants-stack#34]
@jose-garrofe
BootNodeDev/grants-stack#33

**Comment by jose-garrofe** [comment]
Still unable to access Direct Round form on Staging env.

**Comment by jose-garrofe** [comment]
If user clicks "This round doesn't have an end date" we should not only clear the End Date field, but also disable it.

Also the Payout Wallet Address is displayed twice at the last step:
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/9d490874-376c-4df5-aa34-61f197ccf869)

**Comment by nicosampler** [comment]
It is already disabled, but we need to add CSS to it. have you tried to edit the "end round date" if the checkbox is clicked? 

good catch on the Payout, I will take a look.

**Comment by jose-garrofe** [comment]
@nicosampler you are right. It's only the CSS change that's missing, but once the checkbox is checked you can't edit the End Date. Thanks!
