### ISSUE TITLE
Explorer - Add Grants Round Type filter.

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/grants-stack#46]
Description:
We need to include a filter on the Explorer so users can easily see either Direct Grants or Quadratic Funding rounds.
This filter will be a dropdown with the label: Grants Round Type. Options for the filter will be "Direct Grants" and "Quadratic Funding".

Explorer View:
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=481%3A2934&type=design&node-id=1373-4384&viewport=-14342%2C-29938%2C1.27&t=AN7BpbM1ZjsZnhH3-1&scaling=min-zoom&starting-point-node-id=1373%3A4384&show-proto-sidebar=1&mode=design

Filter:
![image.png](https://images.zenhubusercontent.com/628bd9cbdd9f9bef41f85bc4/71968bc7-d7dc-45a6-86e6-38ba56950f6c)

Type label badge:
![image.png](https://images.zenhubusercontent.com/628bd9cbdd9f9bef41f85bc4/cba7754a-eb80-4feb-a2d2-adccce411e2a)

**Comment by marcelorubini** [comment]
@jose-garrofe finished with round type filters and placed the round type badges for all round cards.

ApplyNow section
![Screenshot from 2023-07-28 08-25-44](https://github.com/BootNodeDev/grants-stack/assets/2502507/9d19770f-9919-4b57-ae7b-ff0d9c67a29d)

ActiveRounds section
![Screenshot from 2023-07-28 08-30-07](https://github.com/BootNodeDev/grants-stack/assets/2502507/0b60c7b0-93d8-48ac-b8f1-de6910f38e97)
