### ISSUE TITLE
Pay grantee

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/grants-stack#6]
As a Round Manager user should be able to start a Payout process for all applications that are in Approved status.
If user clicks on an application that's Approved, they will be redirected to the Application Details. In this page user should have a Payout button. 
When user clicks Payout button, they will be redirected to a Payout page where they need to complete Payout Token (selector, token selected on the Round is value by default) and Amount (number) fields.
When both fields are completed, a button labeled Complete should be enabled. If user clicks the button, the Payout process should be triggered.

Update:
Right now there's an option on the Round's left menu to pay grantees (called Fund Grantees)
We need to decide if we will keep this and update it to our work if needed, or remove it completely and only keep the payout option on each application detail page.
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/de7a90e5-8e31-4087-8db0-1fa2c164fd18)

**Comment by marcelorubini** [comment]
https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=35%3A220&type=design&node-id=392-2227&viewport=556%2C566%2C0.15&scaling=min-zoom&starting-point-node-id=64%3A635&t=WoMDvAon7qn0dNVR-1

**Comment by pragalli** [comment]
Total Paid ------- Total Requested

**Comment by pragalli** [comment]
New Payment:

Vault: descripcion
Desahabilitado el Payout hasta el Approval

**Comment by tloffler** [comment]
Payout Figma with the following changes:
- Remove Vault input from the Round creation process
- Add Vault input in the Payout form.
- Disable the payout button if the amount and vault input are not filled.
- Disable the payout and display an alert message if the vault is not approved.

https://www.figma.com/proto/rax6pBts8JLgCh1E58pqf7/Gitcoin?page-id=35%3A220&type=design&node-id=255-1033&viewport=-3603%2C-4258%2C0.92&t=YUZjrNC9ex7S8Z1H-1&scaling=min-zoom&starting-point-node-id=64%3A635&mode=design

**Comment by jose-garrofe** [comment]
@nicosampler Payout functionality is now displayed on ALL applications no matter their status.
Payout section should only be displayed for Approved applications.
