### ISSUE TITLE
Add discussion platform / contact information

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/grants-stack#8]
If a Round Manager has changed an application from Received to In Review status, the Contact Information set on the Round must be shared with the Project on the Builder side on their application.

Round Manager fields where this data is saved:
![image.png](https://images.zenhubusercontent.com/61bc9d4eea7b03e431932ef8/b986db1a-cb01-4b01-98e0-5e37f13a9c1c)

**Comment by InakyMaister** [comment]
`Project Details` on Builder side show contact information even though the Application is still on `Pending` state.

**Screenshots**

![Pending State application broadcasting Contact Information.png](https://images.zenhubusercontent.com/620d3518f7acb7000cf6030b/64f22547-7965-40cb-8ed8-f59dd986bfbe)

![Builder Contact Information While Pending.png](https://images.zenhubusercontent.com/620d3518f7acb7000cf6030b/c2b29948-866c-4940-a7fa-09921739794b)

**Comment by marcelorubini** [comment]
@InakyMaister contact information at Application cards is now rendered only for In Review state:
![Screenshot from 2023-08-04 05-23-40](https://github.com/BootNodeDev/grants-stack/assets/2502507/e42c4e6d-27c2-4cd8-8cc7-6e375664e44a)

Also, at ViewApplication view now is rendered as a mailto link:
![Screenshot from 2023-08-04 05-24-24](https://github.com/BootNodeDev/grants-stack/assets/2502507/f11229eb-cd47-41e2-a1f3-131ccbbe74a6)

**Comment by InakyMaister** [comment]
Great job!

May I suggest a slight modification? See the screenshot below.

![Screenshot 2023-08-04 at 12.38.18.png](https://images.zenhubusercontent.com/620d3518f7acb7000cf6030b/e74db536-710f-4be2-a900-4d148a17d693)

Since the app is granting more actions with every new state, doesn't seem right to remove contact information on a state that's further down the road compare to the one that granted said contact information.

**Comment by marcelorubini** [comment]
@InakyMaister just finished deploying a new instance with the modifications you mentions over the RoundApplication cards and ViewApplication view as well. Thanks for pointing that out :muscle: 

So, for the Contact Information availability:
- In Review & Approved :heavy_check_mark: 
- Received & Rejected :no_entry_sign:
